version: 2.1

jobs:
  release:
    docker:
      - image: cimg/node:14.16
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: GH_TOKEN=$GH_TOKEN npx semantic-release@17

workflows:
  version: 2
  build:
    jobs:
      - release:
          filters:
            branches:
              only:
                - master