version: 2.1

jobs:
  release:
    docker:
      - image: cimg/node:14.16
    steps:
      - checkout
      - run: echo 'export PREV_VERSION='$(git describe --tags --abbrev=0) >> $BASH_ENV
      - run: GH_TOKEN=$GH_TOKEN npx semantic-release@17
      - run: echo 'export CURR_VERSION='$(git describe --tags --abbrev=0) >> $BASH_ENV
      - run: echo $PREV_VERSION
      - run: echo $CURR_VERSION

workflows:
  version: 2
  build:
    jobs:
      - release:
          filters:
            branches:
              only:
                - master